version: '3'

services:
  # Postgres DB
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
#    networks:
#      - app

